Add check to make sure users can only specify env name OR prefix. Not both at the same time.
Previously, they could get away with specifying both. In this case, the prefix was getting selected and name was silently ignored which can lead to confusion.

diff --git a/conda-env-mod b/conda-env-mod
--- a/conda-env-mod
+++ b/conda-env-mod
@@ -611,7 +611,10 @@ fi
 # Logic for environment name and location
 if [ "${ENV_PREFIX}" != "" ]; then
 	CONDA_ARGS+=( --prefix "${ENV_PREFIX}" )
-	if [ "${ENV_NAME}" == "" ]; then
+	if [ "${ENV_NAME}" != "" ]; then
+		echo "Cannot specify both environment name and prefix. Please specify one or the other."
+		exit 1
+	else
 		ENV_NAME="${ENV_PREFIX##*/}"
 	fi
 fi
