Move the module file generation code into a separate script. This way individual sites can create their own templates.

diff --git a/conda-env-mod b/conda-env-mod
--- a/conda-env-mod
+++ b/conda-env-mod
@@ -22,6 +22,12 @@ MODULE_INIT_SCRIPT="/etc/profile.d/modules.sh"
 					# Script to initialize Lmod commands.
 BASE_CONDA_MODULE_NAME="anaconda"	# This is what you call the base
 					# anaconda module.
+DEFAULT_TEMPLATE_DIR="templates/rcac"   #
+                                        #
+SCRIPT_TOP_DIR="$(realpath ${BASH_SOURCE[0]} | xargs dirname)"
+                                        #
+DEFAULT_MODULE_TEMPLATE="${SCRIPT_TOP_DIR}/${DEFAULT_TEMPLATE_DIR}/modules/${ENVIRONMENT_MODULE_TYPE}/default.sh"
+                                        #
 # end configurations                    #
 #########################################
 
@@ -255,60 +261,16 @@ function create_module()
 		mkdir -p "${MODULE_DIR}"
 	fi
 
+	if [ ! -f "${MODULE_TEMPLATE}" ]; then
+		echo "Cannot locate module template: ${MODULE_TEMPLATE}"
+		echo "Aborting module file generation."
+		exit 1
+	fi
+
 	MODULE_FILE="${MODULE_DIR}/${ENV_NAME}-py${PY}.lua"
 	CONDA_MODULE=$(module --redirect --terse list ${BASE_CONDA_MODULE_NAME} | grep "^${BASE_CONDA_MODULE_NAME}\/.*")
 
-	cat <<-EOF > "${MODULE_FILE}"
-		-- created on $(date) by $USER
-
-	EOF
-	if [ "${CONDA_MODULE}" != "" ]; then
-		cat <<-EOF >> "${MODULE_FILE}"
-			depends_on("${CONDA_MODULE}")
-
-		EOF
-	elif [ -f "${CONDA_PREFIX}/bin/conda" ]; then
-		cat <<-EOF >> "${MODULE_FILE}"
-			-- Use the base conda that created this environment.
-			prepend_path("PATH","${CONDA_PREFIX}/bin")
-		EOF
-	else
-		echo -e "WARNING: Couldn't find an anaconda module.\nPlease make sure you to initialize conda separately."
-	fi
-	cat <<-EOF >> "${MODULE_FILE}"
-		local modroot = "${ENV_DIR}"
-		local pyver   = "${PY}"
-
-		local bashStr = 'eval '..modroot..'/bin/pip "\$@"'
-		local cshStr  = "eval "..modroot.."/bin/pip \$*"
-		set_shell_function("pip",bashStr,cshStr)
-		-- If this is Python3 environment, brace against 'pip3', too
-		if (string.match(pyver,"^3%.")) then
-		 	set_shell_function("pip3",bashStr,cshStr)
-		end
-
-		pushenv("CONDA_PREFIX",modroot)
-		pushenv("CONDA_DEFAULT_ENV",modroot)
-		prepend_path("LD_LIBRARY_PATH",modroot.."/lib")
-		prepend_path("PYTHONPATH",modroot.."/lib/python${PY_S}/site-packages")
-		pushenv("PYTHONNOUSERSITE","1")
-	EOF
-	echo >> "${MODULE_FILE}"
-
-	if [[ $Opt_LOCAL_PY -eq 0 ]]; then
-		# if user put down base-python, then use Python from base Anaconda
-		cat <<-EOF >> "${MODULE_FILE}"
-			-- This line is deliberately commented out.
-			-- We want to use Python from base Anaconda.
-			-- prepend_path("PATH",modroot.."/bin")
-		EOF
-	else
-		# python from the environment (python -V) is added to PYTHONPATH by default
-		cat <<-EOF >> "${MODULE_FILE}"
-			-- Using Python and tools from the environment
-			prepend_path("PATH",modroot.."/bin")
-		EOF
-	fi
+	source ${MODULE_TEMPLATE} > ${MODULE_FILE}
 
 	# And concoct instructions for the user.
 	# 'module use' is preferred, but fall back to 'use.own' if available
@@ -531,6 +493,7 @@ fi
 # Set initial values for flags
 MODULE_TOP="${MODULE_TOP_DEF}"
 MODULE_APP="${MODULE_APP_DEF}"
+MODULE_TEMPLATE="${DEFAULT_MODULE_TEMPLATE}"
 CONDA_ARGS=()
 CONDA_XTRA=() 		# CONDA_ARGS are used for -p/-n/-y, XTRA is for packages
 Opt_YES=0
